name: gitignores
base: core18
version: "0.1"
summary: gitignore
description: |
  CLI app that will create a .gitignore file for the project specified by the developer
  for productivity instead of wasting time to get the templates of specific programming 
  projects on the browser.

grade: devel
confinement: devmode

apps:
  gitignore:
    command: gitignore

parts:
  gitignore:
    plugin: dump
    source: .
