name: gitignores
base: core18
version: "0.1"
summary: gitignores
description: |
  CLI app that will create a .gitignore file for the project specified by the developer
  for productivity instead of wasting time to get the templates of specific programming 
  projects on the browser.

grade: stable
confinement: strict

apps:
  gitignore:
    command: bin/gitignores

parts:
  gitignore:
    plugin: dump
    source: .
